### PR TITLE
 Update readme #6

### PR DESCRIPTION
**Pull request by ValchanOficial**
Update readme #6

### CODE REVIEW

**Comment by AndersonQ** [comment]
Hi @ValchanOficial I'm happy to accept PRs improving the Readme, but yours is not adding value. It's removing the formatting. I didn't understand what is your idea

**Comment by ValchanOficial** [comment]
> Hi @ValchanOficial I'm happy to accept PRs improving the Readme, but yours is not adding value. It's removing the formatting. I didn't understand what is your idea

I changed the formatting and added the contributors

**Comment by AndersonQ** [comment]
I see but the formatting was right, and I like the raw `go-skeleton` as the name. With your changes the formatting would be broken.

**Comment by AndersonQ** [comment]
Closing due age, besides seems the branch/fork was deleted

**Pull request closed without merging**
